#!/bin/bash
rm box.dat
rm pairDist.dat
alpha=5
for T in {20..520..50}
do
   echo $T
   ./main.py $T $alpha
   gnuplot movie.gp
   gnuplot velocity.gp
   gnuplot pairdist.gp
   gnuplot movie2.gp
   gnuplot movie3.gp
   mv velocity.gif velocity_$T\.gif
   mv movie.gif movie_$T\_.gif
   mv movie2.gif movie2_$T\_.gif
   mv movie3.gif movie3_$T\_.gif
   mv pairdist.gif pairdist_$T\_.gif
   mv box.dat box_$T\_.dat
   mv pairDist.dat pairDist_$T\_.dat
done
