#!/bin/bash

T=70
for alpha in {0..10..2} 
do
   echo $alpha
   ./main.py $T $alpha
   gnuplot movie.gp
   gnuplot velocity.gp
   gnuplot pairdist.gp
   gnuplot movie2.gp
   gnuplot movie3.gp
   mv velocity.gif velocity_$T\_$alph\_.gif
   mv movie.gif movie_$T\_$alpha\.gif
   mv movie2.gif movie2_$T\_$alpha\.gif
   mv movie3.gif movie3_$T\__$alpha\.gif
   mv pairdist.gif pairdist_$T\_$alpha\.gif
   mv box.dat box_$T\__$alpha\.dat
   mv pairDist.dat pairDist_$T\__$alpha\.dat
done
